using System;
using System.Collections.Generic;
using ClickHouse.Driver.Compression;
using NUnit.Framework;

namespace ClickHouse.Driver.Tests;

/// <summary>
/// Unit tests for <see cref="CityHash102"/>, the CityHash v1.0.2 port that computes the compression
/// frame's checksum.
/// <para>
/// Every expected value below was generated by compiling the reference <c>city.cc</c> that ClickHouse
/// vendors as <c>contrib/cityhash102</c> and hashing the same input, so these pin the port against the
/// implementation the server itself uses rather than against our own output. A modern (1.1+) CityHash
/// fails all of them, which is the confusion this fixture exists to catch.
/// </para>
/// <para>
/// The lengths cover every branch: 0, below 4, 4 to 7, the 8 to 15 case that seeds from an empty span,
/// 16, 17 to 32, the <c>CityMurmur</c> range up to 127, 128 where the unrolled loop starts, and lengths
/// past it whose tail walks backwards over already-consumed bytes.
/// </para>
/// </summary>
[TestFixture]
public class CityHash102Tests
{
    /// <summary>Reference vectors over <see cref="Pattern"/> inputs: length, then the expected low and high halves.</summary>
    private static IEnumerable<TestCaseData> PatternVectors()
    {
        yield return new TestCaseData(0, 0x3df09dfc64c09a2bUL, 0x3cb540c392e51e29UL);
        yield return new TestCaseData(1, 0x8be55b379cce0e40UL, 0x05ab4744478b1cbaUL);
        yield return new TestCaseData(2, 0x701c733aee3382d4UL, 0xba4eae41e0e6dc7aUL);
        yield return new TestCaseData(3, 0xe407deda7bb0f294UL, 0x0a3a0d146e27f1bdUL);
        yield return new TestCaseData(4, 0x905dcb2063ae124fUL, 0x57fd5b5954a593c5UL);
        yield return new TestCaseData(5, 0x69a56895d9ac3ddcUL, 0x955b14ec8ac620d5UL);
        yield return new TestCaseData(7, 0xd7ba2459ab7c2913UL, 0x53dd430b513ca460UL);
        yield return new TestCaseData(8, 0xf5a4ca47208136a0UL, 0x3dd4575b3d46e5abUL);
        yield return new TestCaseData(9, 0x338434c54a2565e1UL, 0x1001bbb07bd33771UL);
        yield return new TestCaseData(12, 0x8450aab120e0ccdcUL, 0x8a990d2011469548UL);
        yield return new TestCaseData(15, 0xd956065c63d9ab15UL, 0x9623caadd0037b73UL);
        yield return new TestCaseData(16, 0x3f3a3275564b7f48UL, 0xb48a2a7a16bac60bUL);
        yield return new TestCaseData(17, 0xaee34bf68bb2e0a2UL, 0xe0d6910555f00b87UL);
        yield return new TestCaseData(24, 0x5adfe1a6eab14c05UL, 0xf76c0804fe96ed75UL);
        yield return new TestCaseData(31, 0x9b7f93e5ecfaed63UL, 0xd646e40154fb0d6bUL);
        yield return new TestCaseData(32, 0x250e8c8007bfad61UL, 0xe42486b6776ae8dbUL);
        yield return new TestCaseData(33, 0x4e495b057af3b520UL, 0xabae1d24f18410b5UL);
        yield return new TestCaseData(63, 0x361db35b3402a110UL, 0x51bf6fff2d8235c5UL);
        yield return new TestCaseData(64, 0xe225cf33b373dc02UL, 0x8d252ce5152d6d96UL);
        yield return new TestCaseData(100, 0x49c189a397bdadeeUL, 0x0e8155bdfd58d3d3UL);
        yield return new TestCaseData(127, 0xc244dc8a06ce8c41UL, 0xf30e2cf6b33629a6UL);
        yield return new TestCaseData(128, 0xba863c0c70f32346UL, 0x24b156fc6f3c170aUL);
        yield return new TestCaseData(129, 0x238598064c8ee2f1UL, 0x6c89b9263ef7410bUL);
        yield return new TestCaseData(160, 0x5cb38c23f218820bUL, 0x28eec84c96793879UL);
        yield return new TestCaseData(191, 0x2f4f8ba535aa5f81UL, 0xb5694954efdb1784UL);
        yield return new TestCaseData(192, 0x45c173eb249e540eUL, 0x64bcb83693c2d72bUL);
        yield return new TestCaseData(255, 0xc87d0f456f6a514bUL, 0xf35b13ec94eb8a52UL);
        yield return new TestCaseData(256, 0xb1cfa883f958dcfaUL, 0x39f0dfb3be182292UL);
        yield return new TestCaseData(1000, 0x597ff4957972ad7eUL, 0x7f39a4abd7c010e1UL);
        yield return new TestCaseData(1048576, 0xd7a7dbcf65ef0f08UL, 0x7b45ba5f2ffeff9aUL);
    }

    /// <summary>Reference vectors over uniform inputs, which catch sign and carry mistakes a varied pattern can hide.</summary>
    private static IEnumerable<TestCaseData> UniformVectors()
    {
        yield return new TestCaseData(25, (byte)0x00, 0xc8596b8135f22993UL, 0xdb2985aef08357b8UL);
        yield return new TestCaseData(25, (byte)0xFF, 0xc5d3cd20b17776e0UL, 0x1bd608e76fe125afUL);
        yield return new TestCaseData(137, (byte)0x00, 0xbfaa109cc5cc6f50UL, 0xb57476dec812081cUL);
        yield return new TestCaseData(137, (byte)0xFF, 0x3381b9cf974f40bcUL, 0x045d59f3d0fa0d6dUL);
    }

    [TestCaseSource(nameof(PatternVectors))]
    public void Hash128_PatternOfLength_MatchesTheReferenceImplementation(int length, ulong expectedLow, ulong expectedHigh)
    {
        var (low, high) = CityHash102.Hash128(Pattern(length));

        Assert.Multiple(() =>
        {
            Assert.That(low, Is.EqualTo(expectedLow), $"low half for length {length}");
            Assert.That(high, Is.EqualTo(expectedHigh), $"high half for length {length}");
        });
    }

    [TestCaseSource(nameof(UniformVectors))]
    public void Hash128_UniformBytes_MatchesTheReferenceImplementation(int length, byte fill, ulong expectedLow, ulong expectedHigh)
    {
        var data = new byte[length];
        data.AsSpan().Fill(fill);

        var (low, high) = CityHash102.Hash128(data);

        Assert.Multiple(() =>
        {
            Assert.That(low, Is.EqualTo(expectedLow), $"low half for {length} x 0x{fill:X2}");
            Assert.That(high, Is.EqualTo(expectedHigh), $"high half for {length} x 0x{fill:X2}");
        });
    }

    [Test]
    public void Hash128_EmptyInput_DoesNotReadTheSpanAndReturnsTheSeededConstant()
    {
        var (low, high) = CityHash102.Hash128(ReadOnlySpan<byte>.Empty);

        Assert.Multiple(() =>
        {
            Assert.That(low, Is.EqualTo(0x3df09dfc64c09a2bUL));
            Assert.That(high, Is.EqualTo(0x3cb540c392e51e29UL));
        });
    }

    [Test]
    public void Hash128_OffsetSliceOfALargerBuffer_HashesOnlyTheSlice()
    {
        // Guards the port's absolute indexing: the tail of a long input walks backwards from the current
        // position, so hashing a slice must not reach bytes outside it.
        var padded = new byte[64 + 200 + 64];
        Pattern(200).CopyTo(padded.AsSpan(64));

        var fromSlice = CityHash102.Hash128(padded.AsSpan(64, 200));
        var standalone = CityHash102.Hash128(Pattern(200));

        Assert.That(fromSlice, Is.EqualTo(standalone));
    }

    /// <summary>The same deterministic input the reference harness hashed: byte i is <c>(i * 31 + 7) &amp; 0xFF</c>.</summary>
    private static byte[] Pattern(int length)
    {
        var data = new byte[length];
        for (int i = 0; i < length; i++)
        {
            data[i] = unchecked((byte)((i * 31) + 7));
        }

        return data;
    }
}
