name: Resolve with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  call-openhands-resolver:
    if: github.actor == 'DarkWanderer'
    uses: DarkWanderer/OpenHands/.github/workflows/openhands-resolver.yml@main
    with:
      macro: '@${{ vars.PAT_USERNAME }}'
      max_iterations: 50
      LLM_MODEL: openai/gpt-4o
      target_branch: ${{ github.event.repository.default_branch }}
    secrets:
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ vars.PAT_USERNAME }}
